name: Build PkCli
permissions:
  contents: write

on:
  push:
    branches:
      - 'prod'
    tags:
        - '*'

jobs:
  build:
    name: 🛠 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🛠️ Install Dependencies
        run: |
          yarn global add pkg
          yarn install

      - name: ⚙️ Build
        run: |
          yarn run build:pkcli
          rm dist/pkcli.js

      - name: 📂 Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_pkcli
          path: |
            dist/

  publish:
    name: 🛠 Publish artifacts
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: 📤 Public Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "🎉 Public Release ${{ github.ref_name }}"
          body: "🎉 Public Release ${{ github.ref_name }}"
          tag_name: "${{ github.ref }}"
          repository: "NukaWorks/Pakagify"
          draft: true
          generate_release_notes: true
          token: ${{ secrets.GH_TOKEN }}
          files: |
            ./**/*
